chore(release): 1.4.0 [skip ci]
# [1.4.0](https://github.com/stoplightio/spectral/compare/@stoplight/spectral-formatters-1.3.0...@stoplight/spectral-formatters-1.4.0) (2024-09-13)

### Bug Fixes

* **cli:** clarify usage of --format ([#2575](https://github.com/stoplightio/spectral/issues/2575)) ([96eee89](https://github.com/stoplightio/spectral/commit/96eee89d3210931b8ffeffe44c44d7e9f610c0b0))
* **core:** fix for TypeError "this.formats.has is not a function" ([#2664](https://github.com/stoplightio/spectral/issues/2664)) ([75d642d](https://github.com/stoplightio/spectral/commit/75d642dae6200136839a8ab67d8860b2e781a8d2))
* **parsers:** update @stoplight/yaml from ~4.2.3 to ~4.3.0 ([91fdded](https://github.com/stoplightio/spectral/commit/91fdded2fcb25880f4ec40091d7d8137f9b64504))
* **repo:** remove discord link and fix typo in github bug template ([#2642](https://github.com/stoplightio/spectral/issues/2642)) ([048924d](https://github.com/stoplightio/spectral/commit/048924d358ccb6432e368ae3d0b15cb78c72a6dd))
* **rulesets:** example validation for required readOnly and writeOnly properties ([#2573](https://github.com/stoplightio/spectral/issues/2573)) ([ae1fea5](https://github.com/stoplightio/spectral/commit/ae1fea50bc37faf7bb230e58158c5d490fc8fb42))
* **rulesets:** fixed array-items type property selector ([#2638](https://github.com/stoplightio/spectral/issues/2638)) ([0845fb5](https://github.com/stoplightio/spectral/commit/0845fb5b27e372161c9dd0454e8176263b042e08))
* **rulesets:** oasExample should clean id fields from non-schema objects ([#2561](https://github.com/stoplightio/spectral/issues/2561)) ([7f7583e](https://github.com/stoplightio/spectral/commit/7f7583e37e9e7d18bc2d7c9ae50939a540b5d720))
* **rulesets:** tweak server variables function ([#2533](https://github.com/stoplightio/spectral/issues/2533)) ([244cbda](https://github.com/stoplightio/spectral/commit/244cbda1256e218d9ab24288e772162b5230323d))
* **rulesets:** use uri-reference for oauth security schemes ([#2652](https://github.com/stoplightio/spectral/issues/2652)) ([c411e63](https://github.com/stoplightio/spectral/commit/c411e63f5fd1bc13c55ee83da0bd0b3120c2a87d))

### Features

* **cli:** add sarif formatter ([#2532](https://github.com/stoplightio/spectral/issues/2532)) ([959a86a](https://github.com/stoplightio/spectral/commit/959a86aedbc0bfe2533212dcaa4e28784fc1e384))
* **formats:** add arazzo format ([#2663](https://github.com/stoplightio/spectral/issues/2663)) ([dc1a8ef](https://github.com/stoplightio/spectral/commit/dc1a8ef003e198ab9943bf50ee17cd64ca2b6307))
* **formats:** jsonSchemaLoose format should search for enum keyword ([#2551](https://github.com/stoplightio/spectral/issues/2551)) ([0835545](https://github.com/stoplightio/spectral/commit/0835545f0b43e7995720bb8a455808f76ef69483))
* **formatters:** add code climate (GitLab) formatter ([#2648](https://github.com/stoplightio/spectral/issues/2648)) ([41eca61](https://github.com/stoplightio/spectral/commit/41eca612d292520142ace3bd97cde630c33366f1))
* **formatters:** add markdown formatter ([#2662](https://github.com/stoplightio/spectral/issues/2662)) ([b5edf5e](https://github.com/stoplightio/spectral/commit/b5edf5e9b61c986097e6d77988489ed12a48611f))
* **rulesets:** add multiple xor ([#2614](https://github.com/stoplightio/spectral/issues/2614)) ([af9c742](https://github.com/stoplightio/spectral/commit/af9c742ef8a9e0749031f41ecf9466e15be9acdd))
* **rulesets:** add new rule that requires sibling items field for type array ([#2632](https://github.com/stoplightio/spectral/issues/2632)) ([24198bc](https://github.com/stoplightio/spectral/commit/24198bcb32eafdeb119ee2432d8488d7a5af14aa))
* **rulesets:** add oas3_1-servers-in-webhook and oas3_1-callbacks-in… ([#2581](https://github.com/stoplightio/spectral/issues/2581)) ([7a8cc0e](https://github.com/stoplightio/spectral/commit/7a8cc0e62c09aca2d579bb81a2602c17028efb49))
* **rulesets:** add scope validation to oas{2,3}-operation-security-defined rules ([#2538](https://github.com/stoplightio/spectral/issues/2538)) ([68aacd6](https://github.com/stoplightio/spectral/commit/68aacd615dc6830ef9d856fcad74f1ec2b2a0ca2))
* **rulesets:** improve {oas2,oas3}-valid-schema rule ([#2574](https://github.com/stoplightio/spectral/issues/2574)) ([8df2c36](https://github.com/stoplightio/spectral/commit/8df2c36d7461a86b3f6fb77fcd1759ed0c3750a0))
* **rulesets:** initial rulesets for the Arazzo Specification ([#2672](https://github.com/stoplightio/spectral/issues/2672)) ([8443232](https://github.com/stoplightio/spectral/commit/84432325cd9eb87c4ce32897bd4a23e83aabb856))