chore(release): 1.0.5 [skip ci]
## [1.0.5](https://github.com/stoplightio/spectral/compare/@stoplight/spectral-ref-resolver-1.0.4...@stoplight/spectral-ref-resolver-1.0.5) (2024-11-13)

### Bug Fixes

* **cli:** choose proxy agent based on requester protocol ([#2521](https://github.com/stoplightio/spectral/issues/2521)) ([056f2e1](https://github.com/stoplightio/spectral/commit/056f2e1eef966b807734fb00aae071411feabe75))
* **cli:** clarify usage of --format ([#2575](https://github.com/stoplightio/spectral/issues/2575)) ([96eee89](https://github.com/stoplightio/spectral/commit/96eee89d3210931b8ffeffe44c44d7e9f610c0b0))
* **cli:** Trigger cli release ([#2695](https://github.com/stoplightio/spectral/issues/2695)) ([c48a929](https://github.com/stoplightio/spectral/commit/c48a9299512343810e267dc2e0fc4d924e4a46a9))
* **cli:** trigger docker release ([920f7b5](https://github.com/stoplightio/spectral/commit/920f7b5b70d89ae4d0a3378602c2fc8ec81a3ebf))
* **cli:** update dependencies and trigger docker release ([c87eacf](https://github.com/stoplightio/spectral/commit/c87eacff7c6d97ec139cc66623e4b0b27158a0cc))
* **core:** fix for TypeError "this.formats.has is not a function" ([#2664](https://github.com/stoplightio/spectral/issues/2664)) ([75d642d](https://github.com/stoplightio/spectral/commit/75d642dae6200136839a8ab67d8860b2e781a8d2))
* **core:** pointer in overrides are applied too broadly ([#2511](https://github.com/stoplightio/spectral/issues/2511)) ([69403c1](https://github.com/stoplightio/spectral/commit/69403c1dc1dd78937bf4dbab3c392f03c76e2201))
* **core:** require new formats version ([#2725](https://github.com/stoplightio/spectral/issues/2725)) ([8ec328f](https://github.com/stoplightio/spectral/commit/8ec328fe68e42519cea1d6afedc4eb309a2c121c))
* **deps:** fix package.json ([0161072](https://github.com/stoplightio/spectral/commit/016107250f88420d224d798c327910faed250d36))
* **formats:** update spectral core version ([6b196da](https://github.com/stoplightio/spectral/commit/6b196dac0a91f433aaf8cff3bbf889f23c31b0ab))
* **formatters:** update spectral core to latest version ([8a382f4](https://github.com/stoplightio/spectral/commit/8a382f4c40cdd2089e3404668c30552300be94eb))
* **functions:** update spectral core to latest ([ede60f3](https://github.com/stoplightio/spectral/commit/ede60f3a99d9fc5ed03747331473dde8b58fa56b))
* **parsers:** update @stoplight/yaml from ~4.2.3 to ~4.3.0 ([91fdded](https://github.com/stoplightio/spectral/commit/91fdded2fcb25880f4ec40091d7d8137f9b64504))
* **repo:** remove discord link and fix typo in github bug template ([#2642](https://github.com/stoplightio/spectral/issues/2642)) ([048924d](https://github.com/stoplightio/spectral/commit/048924d358ccb6432e368ae3d0b15cb78c72a6dd))
* **repo:** update yarn lock ([362cdb4](https://github.com/stoplightio/spectral/commit/362cdb434c56cbc9b64fc54d0d91f899dd89baac))
* **ruleset-migrator:** update @stoplight/json from ~3.20.1 to ~3.21.0 ([3f7eebc](https://github.com/stoplightio/spectral/commit/3f7eebc2ab11b9e78f675dd559369b2aea099a7c))
* **rulesets:** always allow string examples in asyncapi schema ([#2625](https://github.com/stoplightio/spectral/issues/2625)) ([4e2f797](https://github.com/stoplightio/spectral/commit/4e2f7974b623afa51221d426f975e2592a14f963))
* **rulesets:** example validation for required readOnly and writeOnly properties ([#2573](https://github.com/stoplightio/spectral/issues/2573)) ([ae1fea5](https://github.com/stoplightio/spectral/commit/ae1fea50bc37faf7bb230e58158c5d490fc8fb42))
* **rulesets:** fixed array-items type property selector ([#2638](https://github.com/stoplightio/spectral/issues/2638)) ([0845fb5](https://github.com/stoplightio/spectral/commit/0845fb5b27e372161c9dd0454e8176263b042e08))
* **rulesets:** oasExample should clean id fields from non-schema objects ([#2561](https://github.com/stoplightio/spectral/issues/2561)) ([7f7583e](https://github.com/stoplightio/spectral/commit/7f7583e37e9e7d18bc2d7c9ae50939a540b5d720))
* **rulesets:** remove step summary rule ([#2692](https://github.com/stoplightio/spectral/issues/2692)) ([d5a566f](https://github.com/stoplightio/spectral/commit/d5a566f13d831bed76c69c2efe3de7b7a111d6d0))
* **rulesets:** tweak server variables function ([#2533](https://github.com/stoplightio/spectral/issues/2533)) ([244cbda](https://github.com/stoplightio/spectral/commit/244cbda1256e218d9ab24288e772162b5230323d))
* **rulesets:** update spectral core to latest ([d74c2b0](https://github.com/stoplightio/spectral/commit/d74c2b03b41133ff45dde76ccf2551e2c61edf2b))
* **rulesets:** use uri-reference for oauth security schemes ([#2652](https://github.com/stoplightio/spectral/issues/2652)) ([c411e63](https://github.com/stoplightio/spectral/commit/c411e63f5fd1bc13c55ee83da0bd0b3120c2a87d))

### Features

* **cli:** add sarif formatter ([#2532](https://github.com/stoplightio/spectral/issues/2532)) ([959a86a](https://github.com/stoplightio/spectral/commit/959a86aedbc0bfe2533212dcaa4e28784fc1e384))
* **cli:** require new stoplight dependencies ([#2726](https://github.com/stoplightio/spectral/issues/2726)) ([8a736b5](https://github.com/stoplightio/spectral/commit/8a736b557a441e578c498df5af4cf5313c6dc2d5))
* **cli:** require newer version of all Spectral dependencies ([10ddd97](https://github.com/stoplightio/spectral/commit/10ddd97b6609a58c3542dccf4019488095b38064))
* **cli:** trigger release ([87a90b3](https://github.com/stoplightio/spectral/commit/87a90b3cfcc205dcd98fc330d4b82a212ea39ad2))
* **cli:** use hpagent ([#2513](https://github.com/stoplightio/spectral/issues/2513)) ([9b2d347](https://github.com/stoplightio/spectral/commit/9b2d3476996f7763c035380beffd2bf46c6051f9))
* **core:** trigger release ([b73d5e8](https://github.com/stoplightio/spectral/commit/b73d5e8a4b3a74cfde1ee82757edcc5a53ae4f5e))
* **formats:** add arazzo format ([#2663](https://github.com/stoplightio/spectral/issues/2663)) ([dc1a8ef](https://github.com/stoplightio/spectral/commit/dc1a8ef003e198ab9943bf50ee17cd64ca2b6307))
* **formats:** jsonSchemaLoose format should search for enum keyword ([#2551](https://github.com/stoplightio/spectral/issues/2551)) ([0835545](https://github.com/stoplightio/spectral/commit/0835545f0b43e7995720bb8a455808f76ef69483))
* **formatters:** add code climate (GitLab) formatter ([#2648](https://github.com/stoplightio/spectral/issues/2648)) ([41eca61](https://github.com/stoplightio/spectral/commit/41eca612d292520142ace3bd97cde630c33366f1))
* **formatters:** add GitHub Actions formatter ([#2508](https://github.com/stoplightio/spectral/issues/2508)) ([6904927](https://github.com/stoplightio/spectral/commit/69049275e9b39d1b22d8d04ef8a47b630b6b1380))
* **formatters:** add markdown formatter ([#2662](https://github.com/stoplightio/spectral/issues/2662)) ([b5edf5e](https://github.com/stoplightio/spectral/commit/b5edf5e9b61c986097e6d77988489ed12a48611f))
* **formatters:** add sarif formatter ([#2532](https://github.com/stoplightio/spectral/issues/2532)) ([908c308](https://github.com/stoplightio/spectral/commit/908c3081df514dbb11c5f6b379f5ad49442c1e0c))
* **rulesets:** add AsyncAPI v3 support ([#2697](https://github.com/stoplightio/spectral/issues/2697)) ([3d69be7](https://github.com/stoplightio/spectral/commit/3d69be7058e8f25f0697b69fd8317a2aefe313c1))
* **rulesets:** add multiple xor ([#2614](https://github.com/stoplightio/spectral/issues/2614)) ([af9c742](https://github.com/stoplightio/spectral/commit/af9c742ef8a9e0749031f41ecf9466e15be9acdd))
* **rulesets:** add new rule that requires sibling items field for type array ([#2632](https://github.com/stoplightio/spectral/issues/2632)) ([24198bc](https://github.com/stoplightio/spectral/commit/24198bcb32eafdeb119ee2432d8488d7a5af14aa))
* **rulesets:** add oas3_1-servers-in-webhook and oas3_1-callbacks-in… ([#2581](https://github.com/stoplightio/spectral/issues/2581)) ([7a8cc0e](https://github.com/stoplightio/spectral/commit/7a8cc0e62c09aca2d579bb81a2602c17028efb49))
* **rulesets:** add oas3-server-variables rule ([#2526](https://github.com/stoplightio/spectral/issues/2526)) ([4c4de85](https://github.com/stoplightio/spectral/commit/4c4de85f5bfe5a1eb8ecdbfa8b9b9b4d7b8f6031))
* **rulesets:** add scope validation to oas{2,3}-operation-security-defined rules ([#2538](https://github.com/stoplightio/spectral/issues/2538)) ([68aacd6](https://github.com/stoplightio/spectral/commit/68aacd615dc6830ef9d856fcad74f1ec2b2a0ca2))
* **rulesets:** improve {oas2,oas3}-valid-schema rule ([#2574](https://github.com/stoplightio/spectral/issues/2574)) ([8df2c36](https://github.com/stoplightio/spectral/commit/8df2c36d7461a86b3f6fb77fcd1759ed0c3750a0))
* **rulesets:** initial rulesets for the Arazzo Specification ([#2672](https://github.com/stoplightio/spectral/issues/2672)) ([8443232](https://github.com/stoplightio/spectral/commit/84432325cd9eb87c4ce32897bd4a23e83aabb856))